version: '3'

services:
  pg:
    image: postgres:12.3-alpine
    restart: always
    ports:
      - 5555:5432
    environment:
      POSTGRES_PASSWORD: secret
      POSTGRES_USER: krab
      POSTGRES_DB: krab
      
  pgweb:
    restart: always
    image: sosedoff/pgweb
    ports: 
      - 5556:8081
    environment:
      - DATABASE_URL=postgres://krab:secret@pg:5432/krab?sslmode=disable
    depends_on:
      - pg
